# Generated by Django 5.2.1 on 2025-05-09 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.IntegerField()),
                ('person_income', models.FloatField()),
                ('person_emp_exp', models.IntegerField()),
                ('loan_amnt', models.FloatField()),
                ('loan_int_rate', models.FloatField()),
                ('loan_percent_income', models.FloatField()),
                ('cb_person_cred_hist_length', models.IntegerField()),
                ('credit_score', models.IntegerField()),
                ('previous_loan_defaults_on_file', models.IntegerField()),
                ('person_gender_male', models.BooleanField()),
                ('person_education', models.CharField(max_length=20)),
                ('person_home_ownership', models.CharField(max_length=20)),
                ('loan_intent', models.CharField(max_length=20)),
                ('prediction', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
